site_name: CiviRemote Event
site_description: Extended features for CiviCRM events, in particular when an external system is used for registration forms.
site_author: SYSTOPIA
repo_url: https://github.com/systopia/de.systopia.remoteevent

theme:
  name: material

nav:
  - 'Introduction': index.md
  - 'Configuration': configuration.md
  - 'API': api.md
  - 'Extensibility': extensibility.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
